name: PR Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
        code_review:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0  # Ensure full history for git diff      
            - name: Set up Python
              uses: actions/setup-python@v5
              with: 
                python-version: "3.10"
            - name: Run code review
              run: |
                cd scripts
                python code_review.py   
            - name: Upload report (optional)
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: code-review-report
                path: code_review_report.txt
